
spring:
  devtools:
    remote:
      restart:
        enabled: true
  redis:
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 8
  datasource:
          name: test
          url: jdbc:mysql://localhost:3306/machinist?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
          username: root
          password: 123456
          #使用druid数据源
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          filters: stat
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
server:
  port: 8080

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  check-config-location: true
  type-aliases-package: top.joylife.machinist.model.entity
logging:
  config: classpath:logback.xml
  path: ./log/
